### ISSUE TITLE
No images in repository list

### ISSUE THREAD

**Issue by vladkras** [atcol/docker-registry-ui#166]
I tried your new v2-compatible image from #162  and it doesn't work as I expect. Steps to reproduce:
1. Login to https://labs.play-with-docker.com/
2. Start [registry](https://hub.docker.com/_/registry/) `docker run -d -p 5000:5000 --name registry registry:2`
3. Check it with `curl http://localhost:5000/v2/_catalog` or open on browser result: `{"repositories":[]}`  
4. Pull and push image into it
    `docker pull ubuntu`
    `docker tag ubuntu localhost:5000/ubuntu`
    `docker push localhost:5000/ubuntu`
5. Check again. Result: `{"repositories":["ubuntu"]}`
6. Run this registry ui `docker run -d -p 8080:8080 atcol/docker-registry-ui`
6. Open 8080 link. It will be smth like http://ip172-18-0-xx-yourUniqueHash-8080.direct.labs.play-with-docker.com
7. Proceed to /registry/create and add
    API Version: v2
    Protocol: http
    Hostname: http://ip172-18-0-xx-yourUniqueHash-8080.direct.labs.play-with-docker.com (as from above)
    Port: 80
8. Make sure "ping succeeded" and open added registry: /repository/index - nothing here! Tags list is empty.
9. Check docker logs `docker log <container_id>`. Result: 
    2018-03-04 15:03:39,674 [http-nio-8080-exec-1] INFO  web.RepositoryService  - Searching for images fromRegistry{id=1, protocol='http', host='ip172-18-0-16-badvrq9lukr000cm8n70-5000.direct.labs.play-with-docker.com/', port=80, apiVersion='v2', username='null', password='null', repositoryService=docker.registry.web.RepositoryService@31265420, version=1}
2018-03-04 15:03:39,674 [http-nio-8080-exec-1] INFO  web.RepositoryService  - Query provided for searchis null
2018-03-04 15:03:39,675 [http-nio-8080-exec-1] INFO  web.RepositoryService  - Getting repositories fromhttp://ip172-18-0-16-badvrq9lukr000cm8n70-5000.direct.labs.play-with-docker.com//v2/_catalog
2018-03-04 15:03:39,739 [http-nio-8080-exec-1] INFO  web.RepositoryService  - response data for repo list [repositories:[ubuntu]] groovyx.net.http.HttpResponseDecorator@78bf6c75

So, repo is there in list but ui shows nothing. Also as this [SO answer](https://stackoverflow.com/questions/30113726/docker-registry-2-0-api-v2) points out "there is no search endpoint in registry v2". I tried both `-e SEARCH_BACKEND=sqlalchemy` and editing config file directly. No mention of `/search` in [official docs](https://docs.docker.com/registry/spec/api/) too.

**Comment by squidnyan** [comment]
I'll take a look.

**Comment by count-graf** [comment]
Do you have any update?

**Comment by nuxsmin** [comment]
Hello, I've just installed the app and it seems that the repository listing isn't working fine too, since it successfully retrieves the catalog data but no listing is displayed at all.

![captura_001](https://user-images.githubusercontent.com/1775774/38406488-7290e0c4-3975-11e8-83f7-988508c3681a.jpg)

![captura_002](https://user-images.githubusercontent.com/1775774/38406559-e6d633b2-3975-11e8-969e-ebe17fc84abd.jpg)

Do you need any more info about it?, Is there any way to enable debug output?

Thanks for the tool!

Kind regards.

**Comment by DeathKR** [comment]
I have the same situation. List is empty.

**Comment by serhio83** [comment]
+1 the same issue with mine installation

**Comment by coldze** [comment]
+1, same issue.

**Comment by lemz90** [comment]
+1, same issue.

**Comment by shahpranaf** [comment]
+1 same issue

**Comment by pavlovpetr** [comment]
+1

**Comment by Thomas-esimple** [comment]
+1, same issue.

**Comment by happy-python** [comment]
+1, same issue.
`$ curl 127.0.0.1:5000/v2/_catalog` can get the lists of images from my local registries but them aren't displayed in the web-ui.

**Comment by count-graf** [comment]
Looks like @squidnyan is not interested in this project any more.....

**Comment by UndeadJoe** [comment]
+1, same issue

![selection_251](https://user-images.githubusercontent.com/6937605/42569957-f24b4a3e-851a-11e8-8998-876d1e4275a2.png)

**Comment by JulienJarvis** [comment]
+1
same here !

**Comment by dfredell** [comment]
The issue here is that docker-registry-ui doesn't actually support the docker API v2. I have added a few of the methods, but then stopped because I don't know how the application is actually supposed to work. 
I have been using https://hub.docker.com/r/hyper/docker-registry-web/ instead 
![image](https://user-images.githubusercontent.com/8085744/43202946-7660a6da-8fe2-11e8-81ca-31785e0e291e.png)
